/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { FlexProps, IconProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type InputOverridesProps = {
    Input?: PrimitiveOverrideProps<ViewProps>;
    "Group 624493"?: PrimitiveOverrideProps<ViewProps>;
    "Full width box869"?: PrimitiveOverrideProps<ViewProps>;
    "Split box870"?: PrimitiveOverrideProps<ViewProps>;
    "Dark theme bg871"?: PrimitiveOverrideProps<ViewProps>;
    "Light theme bg872"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 624501926"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 62449892"?: PrimitiveOverrideProps<FlexProps>;
    "Group 62576393"?: PrimitiveOverrideProps<FlexProps>;
    Rest94?: PrimitiveOverrideProps<TextProps>;
    "Dropdown / Dropdown95"?: PrimitiveOverrideProps<ViewProps>;
    Base96?: PrimitiveOverrideProps<ViewProps>;
    Text97?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 198"?: PrimitiveOverrideProps<ViewProps>;
    ChevronDownMed99?: PrimitiveOverrideProps<TextProps>;
    "Frame 624500918"?: PrimitiveOverrideProps<FlexProps>;
    "Group 625763919"?: PrimitiveOverrideProps<FlexProps>;
    Rest920?: PrimitiveOverrideProps<TextProps>;
    "Dropdown / Dropdown921"?: PrimitiveOverrideProps<ViewProps>;
    Base922?: PrimitiveOverrideProps<ViewProps>;
    Text923?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 1924"?: PrimitiveOverrideProps<ViewProps>;
    ChevronDownMed925?: PrimitiveOverrideProps<TextProps>;
    "Frame 624502937"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 624498938"?: PrimitiveOverrideProps<FlexProps>;
    "Group 625763939"?: PrimitiveOverrideProps<FlexProps>;
    Rest940?: PrimitiveOverrideProps<TextProps>;
    "Dropdown / Dropdown941"?: PrimitiveOverrideProps<ViewProps>;
    Base942?: PrimitiveOverrideProps<ViewProps>;
    Text943?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 1944"?: PrimitiveOverrideProps<ViewProps>;
    ChevronDownMed945?: PrimitiveOverrideProps<TextProps>;
    "Frame 624500946"?: PrimitiveOverrideProps<FlexProps>;
    "Group 625763947"?: PrimitiveOverrideProps<FlexProps>;
    Rest948?: PrimitiveOverrideProps<TextProps>;
    "Dropdown / Dropdown949"?: PrimitiveOverrideProps<ViewProps>;
    Base950?: PrimitiveOverrideProps<ViewProps>;
    Text951?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 1952"?: PrimitiveOverrideProps<ViewProps>;
    ChevronDownMed953?: PrimitiveOverrideProps<TextProps>;
    "Group 624498"?: PrimitiveOverrideProps<ViewProps>;
    "Full width box10340"?: PrimitiveOverrideProps<ViewProps>;
    "Split box10341"?: PrimitiveOverrideProps<ViewProps>;
    "Dark theme bg10342"?: PrimitiveOverrideProps<ViewProps>;
    "Light theme bg10343"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 62450210361"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 62449810362"?: PrimitiveOverrideProps<FlexProps>;
    "Group 62576310363"?: PrimitiveOverrideProps<FlexProps>;
    Rest10364?: PrimitiveOverrideProps<TextProps>;
    "Dropdown / Dropdown10365"?: PrimitiveOverrideProps<ViewProps>;
    Base10366?: PrimitiveOverrideProps<ViewProps>;
    Base10383?: PrimitiveOverrideProps<ViewProps>;
    Text10367?: PrimitiveOverrideProps<TextProps>;
    ChevronDownMed10369?: PrimitiveOverrideProps<TextProps>;
    "Frame 62450310384"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 62449810385"?: PrimitiveOverrideProps<FlexProps>;
    "Group 62576310386"?: PrimitiveOverrideProps<FlexProps>;
    Rest10387?: PrimitiveOverrideProps<TextProps>;
    "Dropdown / Dropdown10388"?: PrimitiveOverrideProps<ViewProps>;
    Base10389?: PrimitiveOverrideProps<ViewProps>;
    Base10390?: PrimitiveOverrideProps<ViewProps>;
    Text10391?: PrimitiveOverrideProps<TextProps>;
    ChevronDownMed10392?: PrimitiveOverrideProps<TextProps>;
    "Invalid email format.10381"?: PrimitiveOverrideProps<TextProps>;
    "Invalid email format.10393"?: PrimitiveOverrideProps<TextProps>;
    Email10382?: PrimitiveOverrideProps<TextProps>;
    Email10394?: PrimitiveOverrideProps<TextProps>;
    "Group 624497"?: PrimitiveOverrideProps<ViewProps>;
    "Full width box955"?: PrimitiveOverrideProps<ViewProps>;
    "Split box956"?: PrimitiveOverrideProps<ViewProps>;
    "Dark theme bg957"?: PrimitiveOverrideProps<ViewProps>;
    "Light theme bg958"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 624501959"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 624498960"?: PrimitiveOverrideProps<FlexProps>;
    "Group 625763961"?: PrimitiveOverrideProps<FlexProps>;
    Rest962?: PrimitiveOverrideProps<TextProps>;
    "Dropdown / Dropdown963"?: PrimitiveOverrideProps<ViewProps>;
    Base964?: PrimitiveOverrideProps<ViewProps>;
    Text965?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 1966"?: PrimitiveOverrideProps<ViewProps>;
    ChevronDownMed967?: PrimitiveOverrideProps<TextProps>;
    "Frame 6244999113"?: PrimitiveOverrideProps<FlexProps>;
    "Group 6257639114"?: PrimitiveOverrideProps<FlexProps>;
    Rest9115?: PrimitiveOverrideProps<TextProps>;
    "Dropdown / Dropdown9116"?: PrimitiveOverrideProps<ViewProps>;
    Base9117?: PrimitiveOverrideProps<ViewProps>;
    Text9118?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 19119"?: PrimitiveOverrideProps<ViewProps>;
    ChevronDownMed9120?: PrimitiveOverrideProps<TextProps>;
    "Group 6257701410"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 521411"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 531412"?: PrimitiveOverrideProps<ViewProps>;
    "Polygon 21413"?: PrimitiveOverrideProps<IconProps>;
    "Polygon 31414"?: PrimitiveOverrideProps<IconProps>;
    "Frame 6245009121"?: PrimitiveOverrideProps<FlexProps>;
    "Group 6257639122"?: PrimitiveOverrideProps<FlexProps>;
    Rest9123?: PrimitiveOverrideProps<TextProps>;
    "Dropdown / Dropdown9124"?: PrimitiveOverrideProps<ViewProps>;
    Base9125?: PrimitiveOverrideProps<ViewProps>;
    Text9126?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 19127"?: PrimitiveOverrideProps<ViewProps>;
    ChevronDownMed9128?: PrimitiveOverrideProps<TextProps>;
    "Frame 6245019129"?: PrimitiveOverrideProps<FlexProps>;
    "Group 6257639130"?: PrimitiveOverrideProps<FlexProps>;
    Rest9131?: PrimitiveOverrideProps<TextProps>;
    "Dropdown / Dropdown9132"?: PrimitiveOverrideProps<ViewProps>;
    Base9133?: PrimitiveOverrideProps<ViewProps>;
    Text9134?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 19135"?: PrimitiveOverrideProps<ViewProps>;
    ChevronDownMed9136?: PrimitiveOverrideProps<TextProps>;
    "Frame 6245029137"?: PrimitiveOverrideProps<FlexProps>;
    "Group 6257639138"?: PrimitiveOverrideProps<FlexProps>;
    Rest9139?: PrimitiveOverrideProps<TextProps>;
    "Dropdown / Dropdown9140"?: PrimitiveOverrideProps<ViewProps>;
    Base9141?: PrimitiveOverrideProps<ViewProps>;
    Text9142?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 19143"?: PrimitiveOverrideProps<ViewProps>;
    ChevronDownMed9144?: PrimitiveOverrideProps<TextProps>;
    "Frame 6245039145"?: PrimitiveOverrideProps<FlexProps>;
    "Group 6257639146"?: PrimitiveOverrideProps<FlexProps>;
    Rest9147?: PrimitiveOverrideProps<TextProps>;
    "Dropdown / Dropdown9148"?: PrimitiveOverrideProps<ViewProps>;
    Base9149?: PrimitiveOverrideProps<ViewProps>;
    Text9150?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 19151"?: PrimitiveOverrideProps<ViewProps>;
    ChevronDownMed9152?: PrimitiveOverrideProps<TextProps>;
    "Frame 6245049153"?: PrimitiveOverrideProps<FlexProps>;
    "Group 6257639154"?: PrimitiveOverrideProps<FlexProps>;
    Rest9155?: PrimitiveOverrideProps<TextProps>;
    "Dropdown / Dropdown9156"?: PrimitiveOverrideProps<ViewProps>;
    Base9157?: PrimitiveOverrideProps<ViewProps>;
    Text9158?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 19159"?: PrimitiveOverrideProps<ViewProps>;
    ChevronDownMed9160?: PrimitiveOverrideProps<TextProps>;
    "Frame 6245059161"?: PrimitiveOverrideProps<FlexProps>;
    "Group 6257639162"?: PrimitiveOverrideProps<FlexProps>;
    Rest9163?: PrimitiveOverrideProps<TextProps>;
    "Dropdown / Dropdown9164"?: PrimitiveOverrideProps<ViewProps>;
    Base9165?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 19251"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 29252"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 39253"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 49254"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 59255"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 69256"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 79257"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 89258"?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 19167"?: PrimitiveOverrideProps<ViewProps>;
    ChevronDownMed9168?: PrimitiveOverrideProps<TextProps>;
    "Frame 6245069169"?: PrimitiveOverrideProps<FlexProps>;
    "Group 6257639170"?: PrimitiveOverrideProps<FlexProps>;
    Rest9171?: PrimitiveOverrideProps<TextProps>;
    "Dropdown / Dropdown9172"?: PrimitiveOverrideProps<ViewProps>;
    Base9173?: PrimitiveOverrideProps<ViewProps>;
    Text9174?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 19175"?: PrimitiveOverrideProps<ViewProps>;
    ChevronDownMed9176?: PrimitiveOverrideProps<TextProps>;
    "Frame 6245029259"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 6244989260"?: PrimitiveOverrideProps<FlexProps>;
    "Group 6257639261"?: PrimitiveOverrideProps<FlexProps>;
    Rest9262?: PrimitiveOverrideProps<TextProps>;
    "Dropdown / Dropdown9263"?: PrimitiveOverrideProps<ViewProps>;
    Base9264?: PrimitiveOverrideProps<ViewProps>;
    Text9265?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 19266"?: PrimitiveOverrideProps<ViewProps>;
    ChevronDownMed9267?: PrimitiveOverrideProps<TextProps>;
    "Frame 6244999268"?: PrimitiveOverrideProps<FlexProps>;
    "Group 6257639269"?: PrimitiveOverrideProps<FlexProps>;
    Rest9270?: PrimitiveOverrideProps<TextProps>;
    "Dropdown / Dropdown9271"?: PrimitiveOverrideProps<ViewProps>;
    Base9272?: PrimitiveOverrideProps<ViewProps>;
    Text9273?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 19274"?: PrimitiveOverrideProps<ViewProps>;
    ChevronDownMed9275?: PrimitiveOverrideProps<TextProps>;
    "Group 625770149"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 52143"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 53147"?: PrimitiveOverrideProps<ViewProps>;
    "Polygon 2145"?: PrimitiveOverrideProps<IconProps>;
    "Polygon 3148"?: PrimitiveOverrideProps<IconProps>;
    "Frame 6245009276"?: PrimitiveOverrideProps<FlexProps>;
    "Group 6257639277"?: PrimitiveOverrideProps<FlexProps>;
    Rest9278?: PrimitiveOverrideProps<TextProps>;
    "Dropdown / Dropdown9279"?: PrimitiveOverrideProps<ViewProps>;
    Base9280?: PrimitiveOverrideProps<ViewProps>;
    Text9281?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 19282"?: PrimitiveOverrideProps<ViewProps>;
    ChevronDownMed9283?: PrimitiveOverrideProps<TextProps>;
    "Frame 6245019284"?: PrimitiveOverrideProps<FlexProps>;
    "Group 6257639285"?: PrimitiveOverrideProps<FlexProps>;
    Rest9286?: PrimitiveOverrideProps<TextProps>;
    "Dropdown / Dropdown9287"?: PrimitiveOverrideProps<ViewProps>;
    Base9288?: PrimitiveOverrideProps<ViewProps>;
    Text9289?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 19290"?: PrimitiveOverrideProps<ViewProps>;
    ChevronDownMed9291?: PrimitiveOverrideProps<TextProps>;
    "Frame 6245029292"?: PrimitiveOverrideProps<FlexProps>;
    "Group 6257639293"?: PrimitiveOverrideProps<FlexProps>;
    Rest9294?: PrimitiveOverrideProps<TextProps>;
    "Dropdown / Dropdown9295"?: PrimitiveOverrideProps<ViewProps>;
    Base9296?: PrimitiveOverrideProps<ViewProps>;
    Text9297?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 19298"?: PrimitiveOverrideProps<ViewProps>;
    ChevronDownMed9299?: PrimitiveOverrideProps<TextProps>;
    "Frame 6245039300"?: PrimitiveOverrideProps<FlexProps>;
    "Group 6257639301"?: PrimitiveOverrideProps<FlexProps>;
    Rest9302?: PrimitiveOverrideProps<TextProps>;
    "Dropdown / Dropdown9303"?: PrimitiveOverrideProps<ViewProps>;
    Base9304?: PrimitiveOverrideProps<ViewProps>;
    Text9305?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 19306"?: PrimitiveOverrideProps<ViewProps>;
    ChevronDownMed9307?: PrimitiveOverrideProps<TextProps>;
    "Frame 6245049308"?: PrimitiveOverrideProps<FlexProps>;
    "Group 6257639309"?: PrimitiveOverrideProps<FlexProps>;
    Rest9310?: PrimitiveOverrideProps<TextProps>;
    "Dropdown / Dropdown9311"?: PrimitiveOverrideProps<ViewProps>;
    Base9312?: PrimitiveOverrideProps<ViewProps>;
    Text9313?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 19314"?: PrimitiveOverrideProps<ViewProps>;
    ChevronDownMed9315?: PrimitiveOverrideProps<TextProps>;
    "Frame 6245059316"?: PrimitiveOverrideProps<FlexProps>;
    "Group 6257639317"?: PrimitiveOverrideProps<FlexProps>;
    Rest9318?: PrimitiveOverrideProps<TextProps>;
    "Dropdown / Dropdown9319"?: PrimitiveOverrideProps<ViewProps>;
    Base9320?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 19321"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 29322"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 39323"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 49324"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 59325"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 69326"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 79327"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 89328"?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 19329"?: PrimitiveOverrideProps<ViewProps>;
    ChevronDownMed9330?: PrimitiveOverrideProps<TextProps>;
    "Frame 6245069331"?: PrimitiveOverrideProps<FlexProps>;
    "Group 6257639332"?: PrimitiveOverrideProps<FlexProps>;
    Rest9333?: PrimitiveOverrideProps<TextProps>;
    "Dropdown / Dropdown9334"?: PrimitiveOverrideProps<ViewProps>;
    Base9335?: PrimitiveOverrideProps<ViewProps>;
    Text9336?: PrimitiveOverrideProps<TextProps>;
    "Rectangle 19337"?: PrimitiveOverrideProps<ViewProps>;
    ChevronDownMed9338?: PrimitiveOverrideProps<TextProps>;
} & EscapeHatchProps;
export declare type InputProps = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: InputOverridesProps | undefined | null;
}>;
export default function Input(props: InputProps): React.ReactElement;
