/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { EscapeHatchProps } from "@aws-amplify/ui-react/internal";
import { FlexProps, IconProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
import { SliderProps } from "./Slider";
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type TcjOverridesProps = {
    Tcj?: PrimitiveOverrideProps<ViewProps>;
    "Simple Slider Example"?: PrimitiveOverrideProps<TextProps>;
    "Group 624493"?: PrimitiveOverrideProps<ViewProps>;
    "Full width box1418"?: PrimitiveOverrideProps<ViewProps>;
    "Split box1419"?: PrimitiveOverrideProps<ViewProps>;
    "Dark theme bg1420"?: PrimitiveOverrideProps<ViewProps>;
    "Light theme bg1421"?: PrimitiveOverrideProps<ViewProps>;
    "Group 62577515318"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1615319"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1715320"?: PrimitiveOverrideProps<ViewProps>;
    Text15321?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 215322"?: PrimitiveOverrideProps<IconProps>;
    "Group 62577615323"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1615324"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1715325"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 62450715326"?: PrimitiveOverrideProps<FlexProps>;
    Text15327?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 215328"?: PrimitiveOverrideProps<IconProps>;
    "Group 62577715329"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1615330"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1715331"?: PrimitiveOverrideProps<ViewProps>;
    Text15332?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 215333"?: PrimitiveOverrideProps<IconProps>;
    slider?: SliderProps;
    "Group 62577815334"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1615335"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1715336"?: PrimitiveOverrideProps<ViewProps>;
    Text15337?: PrimitiveOverrideProps<TextProps>;
    Text15338?: PrimitiveOverrideProps<TextProps>;
    Text15339?: PrimitiveOverrideProps<TextProps>;
    Text15340?: PrimitiveOverrideProps<TextProps>;
    Text15341?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 215342"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 315343"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 415344"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 515345"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 615346"?: PrimitiveOverrideProps<IconProps>;
    "Group 624494"?: PrimitiveOverrideProps<ViewProps>;
    "Full width box15348"?: PrimitiveOverrideProps<ViewProps>;
    "Split box15349"?: PrimitiveOverrideProps<ViewProps>;
    "Dark theme bg15350"?: PrimitiveOverrideProps<ViewProps>;
    "Light theme bg15351"?: PrimitiveOverrideProps<ViewProps>;
    "Group 625771"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1615353"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1715354"?: PrimitiveOverrideProps<ViewProps>;
    Text15355?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 215356"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 315412"?: PrimitiveOverrideProps<IconProps>;
    "Group 62577515418"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1615419"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1715420"?: PrimitiveOverrideProps<ViewProps>;
    Text15421?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 215422"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 315423"?: PrimitiveOverrideProps<IconProps>;
    "Group 625774"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1615363"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1715364"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 62450715365"?: PrimitiveOverrideProps<FlexProps>;
    Text15366?: PrimitiveOverrideProps<TextProps>;
    "Frame 62450815416"?: PrimitiveOverrideProps<FlexProps>;
    Text15417?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 215367"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 315415"?: PrimitiveOverrideProps<IconProps>;
    "Group 62577615424"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1615425"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1715426"?: PrimitiveOverrideProps<ViewProps>;
    "Frame 62450715427"?: PrimitiveOverrideProps<FlexProps>;
    Text15428?: PrimitiveOverrideProps<TextProps>;
    "Frame 62450815429"?: PrimitiveOverrideProps<FlexProps>;
    Text15430?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 215431"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 315432"?: PrimitiveOverrideProps<IconProps>;
    "Group 625773"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1615375"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1715376"?: PrimitiveOverrideProps<ViewProps>;
    Text15377?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 215378"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 315414"?: PrimitiveOverrideProps<IconProps>;
    "Group 62577715433"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1615434"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1715435"?: PrimitiveOverrideProps<ViewProps>;
    Text15436?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 215437"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 315438"?: PrimitiveOverrideProps<IconProps>;
    "Group 625772"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1615385"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1715386"?: PrimitiveOverrideProps<ViewProps>;
    Text15387?: PrimitiveOverrideProps<TextProps>;
    Text15388?: PrimitiveOverrideProps<TextProps>;
    Text15389?: PrimitiveOverrideProps<TextProps>;
    Text15390?: PrimitiveOverrideProps<TextProps>;
    Text15391?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 215392"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 715413"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 415394"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 515395"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 615396"?: PrimitiveOverrideProps<IconProps>;
    "Group 62577815439"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1615440"?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1715441"?: PrimitiveOverrideProps<ViewProps>;
    Text15442?: PrimitiveOverrideProps<TextProps>;
    Text15443?: PrimitiveOverrideProps<TextProps>;
    Text15444?: PrimitiveOverrideProps<TextProps>;
    Text15445?: PrimitiveOverrideProps<TextProps>;
    Text15446?: PrimitiveOverrideProps<TextProps>;
    "Ellipse 215447"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 715448"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 415449"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 515450"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 615451"?: PrimitiveOverrideProps<IconProps>;
    States14198?: PrimitiveOverrideProps<FlexProps>;
    Title14199?: PrimitiveOverrideProps<TextProps>;
    States15410?: PrimitiveOverrideProps<FlexProps>;
    Title15411?: PrimitiveOverrideProps<TextProps>;
} & EscapeHatchProps;
export declare type TcjProps = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: TcjOverridesProps | undefined | null;
}>;
export default function Tcj(props: TcjProps): React.ReactElement;
